version: "3.8"
services:
  agent1:
    image: aztecprotocol/aztec:latest
    command: [ "node", "--no-warnings", "/usr/src/yarn-project/aztec/dest/bin/index.js", "start", "--prover-agent", "--network", "alpha-testnet" ]
    entrypoint: >
      sh -c 'node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --network alpha-testnet --prover-agent'
    environment:
      PROVER_AGENT_COUNT: "3"
      PROVER_AGENT_POLL_INTERVAL_MS: "10000"
      PROVER_BROKER_HOST: http://${BROKER_IP}:8080
      PROVER_ID: "1"
    restart: unless-stopped
    volumes:
      - ./data-prover:/data-prover

  agent2:
    image: aztecprotocol/aztec:latest
    command: [ "node", "--no-warnings", "/usr/src/yarn-project/aztec/dest/bin/index.js", "start", "--prover-agent", "--network", "alpha-testnet" ]
    entrypoint: >
      sh -c 'node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --network alpha-testnet --prover-agent'
    environment:
      PROVER_AGENT_COUNT: "3"
      PROVER_AGENT_POLL_INTERVAL_MS: "10000"
      PROVER_BROKER_HOST: http://${BROKER_IP}:8080
      PROVER_ID: "2"
    restart: unless-stopped
    volumes:
      - ./data-prover:/data-prover

  agent3:
    image: aztecprotocol/aztec:latest
    command: [ "node", "--no-warnings", "/usr/src/yarn-project/aztec/dest/bin/index.js", "start", "--prover-agent", "--network", "alpha-testnet" ]
    entrypoint: >
      sh -c 'node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --network alpha-testnet --prover-agent'
    environment:
      PROVER_AGENT_COUNT: "3"
      PROVER_AGENT_POLL_INTERVAL_MS: "10000"
      PROVER_BROKER_HOST: http://${BROKER_IP}:8080
      PROVER_ID: "3"
    restart: unless-stopped
    volumes:
      - ./data-prover:/data-prover

  agent4:
    image: aztecprotocol/aztec:latest
    command: [ "node", "--no-warnings", "/usr/src/yarn-project/aztec/dest/bin/index.js", "start", "--prover-agent", "--network", "alpha-testnet" ]
    entrypoint: >
      sh -c 'node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --network alpha-testnet --prover-agent'
    environment:
      PROVER_AGENT_COUNT: "3"
      PROVER_AGENT_POLL_INTERVAL_MS: "10000"
      PROVER_BROKER_HOST: http://${BROKER_IP}:8080
      PROVER_ID: "4"
    restart: unless-stopped
    volumes:
      - ./data-prover:/data-prover
