name: aztec-sequencer-node-${ID}
services:
  sequencer-node:
    image: aztecprotocol/aztec:1.2.1
    environment:
      ETHEREUM_HOSTS: ${ETHEREUM_HOSTS}
      L1_CONSENSUS_HOST_URLS: ${L1_CONSENSUS_HOST_URLS}
      DATA_DIRECTORY: /data
      VALIDATOR_PRIVATE_KEY: ${VALIDATOR_PRIVATE_KEY}
      P2P_IP: ${P2P_IP}
      LOG_LEVEL: debug
    entrypoint: >
      sh -c 'node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --network alpha-testnet start --node --archiver --sequencer'
    ports:
      - ${P2P_PORT}:40400/tcp
      - ${P2P_PORT}:40400/udp
      - ${API_PORT}:8080
    restart: always
    volumes:
      - /root/aztec-sequencer-node-${ID}/data:/data # Local directory
